//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module fpga_vga(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);

//=======================================================
//  REG/WIRE declarations
//=======================================================

// Khai báo dây nối nội bộ giữa các module
wire clk_25m175;
wire rst_n;
wire video_on;
wire [9:0] pixel_x;
wire [9:0] pixel_y;

// Gán nút KEY[0] làm tín hiệu Reset hệ thống (Active Low)
assign rst_n = KEY[0];

//=======================================================
//  Structural coding
//=======================================================

// 1. Khởi tạo IP PLL (Tạo 25.175MHz từ nguồn 50MHz) [cite: 13, 25]
// Lưu ý: Tên port (refclk, rst, outclk_0) phải khớp chính xác với file IP PLL bạn đã sinh ra.
pll_25m175 u_pll (
	.refclk   (CLOCK_50),   // Cấp clock nguồn 50MHz từ board [cite: 13]
	.rst      (~rst_n),     // Hầu hết Altera PLL yêu cầu reset Active High, nên đảo bit của rst_n
	.outclk_0 (clk_25m175), // Xuất ra 25.175MHz [cite: 18, 25]
	.locked   ()            // Bỏ trống nếu không sử dụng cờ báo trạng thái locked
);

// 2. Khởi tạo khối VGA Timing (Sinh HSYNC, VSYNC, đếm pixel) [cite: 16]
vga_timing u_vga_timing (
	.clk_25m175 (clk_25m175),
	.rst_n      (rst_n),
	.hsync      (VGA_HS),     // Nối trực tiếp ra chân VGA_HS của board [cite: 13]
	.vsync      (VGA_VS),     // Nối trực tiếp ra chân VGA_VS của board [cite: 13]
	.video_on   (video_on),
	.pixel_x    (pixel_x),
	.pixel_y    (pixel_y)
);

// 3. Khởi tạo khối xuất Color Bar [cite: 17]
color_bar_pattern u_color_bar (
	.pixel_x  (pixel_x),
	.pixel_y  (pixel_y),
	.video_on (video_on),
	.vga_r    (VGA_R),        // Nối trực tiếp ra mảng chân VGA_R (8 bit) [cite: 13]
	.vga_g    (VGA_G),        // Nối trực tiếp ra mảng chân VGA_G (8 bit) [cite: 13]
	.vga_b    (VGA_B)         // Nối trực tiếp ra mảng chân VGA_B (8 bit) [cite: 13]
);

// 4. Gắn các tín hiệu điều khiển bổ sung cho VGA DAC
assign VGA_CLK     = clk_25m175; // Bắt buộc phải cấp clock pixel cho chip DAC để chốt dữ liệu
assign VGA_BLANK_N = video_on;   // Cấp tín hiệu cho DAC biết vùng không hiển thị để làm đen (Active Low)
assign VGA_SYNC_N  = 1'b0;       // Không dùng tính năng Sync-on-Green (Thường nối mức 0 trên DE10-Standard)

endmodule